import type { Metadata } from "next";
import "@/app/styles/globals.scss";
import { Footer } from "@/app/layouts/Footer";
import { Navbar } from "@/app/layouts/Navbar";
import { Raleway } from "next/font/google";

const raleway = Raleway({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Navbar />
        {children}
        <Footer />
        <div id="portal"></div>
      </body>
    </html>
  );
}
